/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacao;

import Core.ConexaoBanco;
import Core.Sessao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Maria Juliana
 */
public class Login extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TelaLogin
     */
    public Login() {        
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        initComponents();
        txtNomeUsuario.setText("bruno");
        txtSenhaUsuario.setText("123");
        centralize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtUsuario = new javax.swing.JLabel();
        txtSenha = new javax.swing.JLabel();
        txtNomeUsuario = new javax.swing.JTextField();
        txtSenhaUsuario = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        JButtonEntrar = new javax.swing.JButton();
        JButtonLimpar = new javax.swing.JButton();
        JLabelEntrar = new javax.swing.JLabel();
        JLabelLimpar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUsuario.setText("Usuário:");

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSenha.setText("Senha:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/matrix-systems.png"))); // NOI18N

        JButtonEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/entrar.png"))); // NOI18N

        JButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar.png"))); // NOI18N

        JLabelEntrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLabelEntrar.setText("ENTRAR");

        JLabelLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLabelLimpar.setText("LIMPAR");
        
        //Adiciona eventos
        JButtonEntrar.addActionListener(this);
        JButtonLimpar.addActionListener(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeUsuario)
                    .addComponent(txtSenhaUsuario)
                    .addComponent(txtSenha)
                    .addComponent(txtUsuario)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButtonEntrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(JLabelEntrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(JLabelLimpar))
                            .addComponent(JButtonLimpar))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButtonEntrar)
                            .addComponent(JButtonLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelLimpar)
                    .addComponent(JLabelEntrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public void centralize() {	
        Dimension T = Toolkit.getDefaultToolkit().getScreenSize();

        Dimension J = getSize();

        if (J.height > T.height) setSize(J.width,T.height); 
        if (J.width > T.width) setSize(T.width,J.height); 

        setLocation((T.width - J.width )/2,(T.height-J.height)/2);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);                
            }
        });        
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JButtonEntrar;
    private javax.swing.JButton JButtonLimpar;
    private javax.swing.JLabel JLabelEntrar;
    private javax.swing.JLabel JLabelLimpar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JLabel txtSenha;
    private javax.swing.JPasswordField txtSenhaUsuario;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource() == JButtonEntrar){
            if(!"".equals(txtNomeUsuario.getText()) && !"".equals(txtSenhaUsuario.getText())){
                try {
                    ConexaoBanco cn = new ConexaoBanco();
                    ResultSet rs;
                    rs = cn.executar("SELECT count(usrNome) FROM usuarios WHERE usrNome ='" + txtNomeUsuario.getText().toLowerCase() + "' AND usrSenha = '" + txtSenhaUsuario.getText().toLowerCase() + "'");
                    rs.next();
                    if(rs.getInt(1) == 1) {
                        Aplicacao.MenuPrincipal menu = new MenuPrincipal();
                        
                        rs = cn.executar("SELECT usrAdministrador FROM usuarios WHERE usrNome ='" + txtNomeUsuario.getText().toLowerCase() + "' AND usrSenha = '" + txtSenhaUsuario.getText().toLowerCase() + "'");
                        rs.next();
                        Sessao sessao = Sessao.getInstance();
                        if("S".equals(rs.getString(1).toUpperCase())){                            
                            sessao.setAdm(true);
                        }else{
                            sessao.setAdm(false);
                            
                        }
                        sessao.setUser(txtNomeUsuario.getText());
                        sessao.setSenha(txtSenhaUsuario.getText());
                        menu.setVisible(true);
                        txtNomeUsuario.setText("");
                        txtSenhaUsuario.setText("");
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Usuário ou senha inválido");
                        txtNomeUsuario.setText("");
                        txtSenhaUsuario.setText("");
                    }
                    
                } catch (SQLException error) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro com banco de dados. " + error.getMessage());
                } catch (Exception error) {
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro. " + error.getMessage());
                }               
            }else{
                JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
            }
        }
        if(e.getSource() == JButtonLimpar){
            txtNomeUsuario.setText("");
            txtSenhaUsuario.setText("");
        }
        
    }
}
