/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Maria Juliana
 */
public class MenuPrincipal extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtGerenciamento = new javax.swing.JLabel();
        JButtonOrdemdeServico = new javax.swing.JButton();
        JButtonContasaReceber = new javax.swing.JButton();
        JButtonFuncionario = new javax.swing.JButton();
        JButtonServiços = new javax.swing.JButton();
        JButtonNotasFiscais = new javax.swing.JButton();
        JButtonBackupeRestauracao = new javax.swing.JButton();
        JButtonRelatorioOrdemdeServico = new javax.swing.JButton();
        JButtonEmitente = new javax.swing.JButton();
        JButtonCliente = new javax.swing.JButton();
        JButtonAjuda = new javax.swing.JButton();
        txtAjuda = new javax.swing.JLabel();
        JButtonLogoff = new javax.swing.JButton();
        txtLogoff = new javax.swing.JLabel();
        JButtonRelatorioContasaReceber = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenuUsuarios = new javax.swing.JMenu();
        JMenuCriacaoUsuarios = new javax.swing.JMenuItem();
        JMenuAlteracaoUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal - Matrix OS");

        txtGerenciamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGerenciamento.setText("Gerenciamento");

        JButtonOrdemdeServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/os.png"))); // NOI18N

        JButtonContasaReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contas-receber-2.png"))); // NOI18N
        JButtonContasaReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonContasaReceberActionPerformed(evt);
            }
        });

        JButtonFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionario.png"))); // NOI18N
        JButtonFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonFuncionarioActionPerformed(evt);
            }
        });

        JButtonServiços.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/servicos.png"))); // NOI18N

        JButtonNotasFiscais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nota-fiscal-eletronica-s-f.png"))); // NOI18N
        JButtonNotasFiscais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNotasFiscaisActionPerformed(evt);
            }
        });

        JButtonBackupeRestauracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone-backup-menor.png"))); // NOI18N

        JButtonRelatorioOrdemdeServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N

        JButtonEmitente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dados-emitente-low.png"))); // NOI18N
        JButtonEmitente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEmitenteActionPerformed(evt);
            }
        });

        JButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N

        JButtonAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao-ajuda.gif"))); // NOI18N

        txtAjuda.setText("Ajuda");

        JButtonLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoff.png"))); // NOI18N

        txtLogoff.setText("Logoff");

        JButtonRelatorioContasaReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relatorio.png"))); // NOI18N

        JMenuUsuarios.setText("Usuários");

        JMenuCriacaoUsuarios.setText("Criação de Usuários");
        JMenuUsuarios.add(JMenuCriacaoUsuarios);

        JMenuAlteracaoUsuarios.setText("Alteração de Usuários");
        JMenuUsuarios.add(JMenuAlteracaoUsuarios);

        jMenuBar1.add(JMenuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JButtonContasaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(JButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 215, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JButtonNotasFiscais, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JButtonBackupeRestauracao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JButtonServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JButtonOrdemdeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonRelatorioContasaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonRelatorioOrdemdeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonAjuda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtAjuda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonLogoff)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JButtonLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLogoff))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JButtonAjuda)
                                    .addComponent(txtGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAjuda)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JButtonOrdemdeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JButtonFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonServiços, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JButtonEmitente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JButtonBackupeRestauracao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButtonContasaReceber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JButtonNotasFiscais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JButtonRelatorioContasaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(JButtonRelatorioOrdemdeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        
        JButtonOrdemdeServico.addActionListener(this);
        JButtonContasaReceber.addActionListener(this);
        JButtonFuncionario.addActionListener(this); 
        JButtonServiços.addActionListener(this); 
        JButtonNotasFiscais.addActionListener(this); 
        JButtonBackupeRestauracao.addActionListener(this); 
        JButtonRelatorioOrdemdeServico.addActionListener(this);
        JButtonEmitente.addActionListener(this); 
        JButtonCliente.addActionListener(this); 
        JButtonAjuda.addActionListener(this); 
        
    }// </editor-fold>                        

    private void JButtonContasaReceberActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void JButtonNotasFiscaisActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void JButtonFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void JButtonEmitenteActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton JButtonAjuda;
    private javax.swing.JButton JButtonBackupeRestauracao;
    private javax.swing.JButton JButtonCliente;
    private javax.swing.JButton JButtonContasaReceber;
    private javax.swing.JButton JButtonEmitente;
    private javax.swing.JButton JButtonFuncionario;
    private javax.swing.JButton JButtonLogoff;
    private javax.swing.JButton JButtonNotasFiscais;
    private javax.swing.JButton JButtonOrdemdeServico;
    private javax.swing.JButton JButtonRelatorioContasaReceber;
    private javax.swing.JButton JButtonRelatorioOrdemdeServico;
    private javax.swing.JButton JButtonServiços;
    private javax.swing.JMenuItem JMenuAlteracaoUsuarios;
    private javax.swing.JMenuItem JMenuCriacaoUsuarios;
    private javax.swing.JMenu JMenuUsuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel txtAjuda;
    private javax.swing.JLabel txtGerenciamento;
    private javax.swing.JLabel txtLogoff;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent botao) {
         if (botao.getSource() == JButtonCliente) {             
             Aplicacao.Cliente c = new Aplicacao.Cliente();             
         }else if(botao.getSource() == JButtonContasaReceber){
             Aplicacao.ConsultaContasReceber cons = new Aplicacao.ConsultaContasReceber();
         }else if(botao.getSource() == JButtonEmitente){
             Aplicacao.CadastroDoEmitente emi = new Aplicacao.CadastroDoEmitente();
         }else if(botao.getSource() == JButtonFuncionario){
             Aplicacao.Funcionario fun = new Aplicacao.Funcionario();
         }else if(botao.getSource() == JButtonNotasFiscais){
             Aplicacao.ConsultaNotaFiscal not = new Aplicacao.ConsultaNotaFiscal();
         }else if(botao.getSource() == JButtonOrdemdeServico){
             Aplicacao.OrdemServico os = new Aplicacao.OrdemServico();
         }else if(botao.getSource() == JButtonServiços){
             Aplicacao.Servicos svc = new Aplicacao.Servicos();
         }
    }
}